modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasForms.png"
license="Restricted"

[[mods]]
modId="hellasforms"
version="2.8.0"
displayName="HellasForms"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise, pg13snipez, xGlitzerschaf, NouveauLumi√®re"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellasforms]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.12,9.1.14)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="tconstruct"
    mandatory=false
    versionRange="[3.3.+,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="hellascontrol"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
